### PR TITLE
Continuous benchmarking

### PR DESCRIPTION
**Pull request by mjskay**
#### Summary

This PR adds continuous benchmarking using {touchstone}, closing #159. Once merged to master, it *should* automatically update PRs with a comment summarizing benchmark results (it won't do this until it is on master).

I've included two starter sets of benchmarks for the `as_draws_XXX` functions and for the `summarise_draws` function.

Thoughts? No idea if this will quite do what we want but I think it's a start. Feedback welcome.

#### Copyright and Licensing

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the following licenses:

- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by mjskay** [comment]
Ah while I'm at it, the ubuntu version in the CMD CHECK github workflow was out of date (no runners for it anymore), so I updated that too.

**Comment by paul-buerkner** [comment]
Thank you! Upon a quick look, I think this is sensible. Do you want me to merge this PR already @mjskay ?

**Comment by mjskay** [comment]
Sure, if you're okay with merging @paul-buerkner that would be great. I can't test the benchmarking much more until it is on `master` since some of the triggers don't work unless they are on the default branch. I think this is in a good enough state to be merged to master now, and then we can go from there.

**Comment by paul-buerkner** [comment]
Perfect. Merging now.

**Pull request merged**
