### PR TITLE
Add handling behaviour for NULL for *_ids(), variables() and n*()

### LINKED ISSUE #78: Is variables(NULL), niterations(NULL), etc. throwing intentional?
Example:
```
> posterior::variables(NULL)
Error in UseMethod("variables") : 
  no applicable method for 'variables' applied to an object of class "NULL"
```
Should it maybe return NULL instead silently, niterations(NULL) would return 0, etc? Or is this and intentional decision?

### PR DESCRIPTION
**Pull request by rok-cesnovar**
Fixes #78

### CODE REVIEW

**Comment by paul-buerkner** [comment]
Thank you! Would you be ok with me moving the treatment of `NULL` outside of the generic and inside of a `*.NULL` method?

**Comment by rok-cesnovar** [comment]
Done that in my first attempt but missed the export so got nowhere :). It should be fine now.

**Comment by paul-buerkner** [comment]
Looks good to me! Thank you! Will merge this now.

**Comment by paul-buerkner** [comment]
I have also added you as a contributor to the package.

**Comment by rok-cesnovar** [comment]
That is very kind of you! Thanks!

**Comment by jgabry** [comment]
Thanks @rok-cesnovar!

**Pull request merged**
