### PR TITLE
Tibble fixes

### LINKED ISSUE #202: Drop draws_df class if meta-data removed by dplyr verbs
From [this comment](https://github.com/stan-dev/posterior/issues/69#issuecomment-914659080):

> Reading more about this on the dplyr side, probably the right thing to do is for us to implement `dplyr::dplyr_reconstruct()` for the `"draws_df"` class in a similar way to `[.draws_df` so that it drops the class if required columns are removed (possibly with a warning like `[.draws_df` does, or maybe not?). We should be able to do this while keeping `dplyr` in suggests. See [here](https://dplyr.tidyverse.org/reference/dplyr_extending.html).

### LINKED ISSUE #210: implement pillar::format_glimpse() for rvars
Currently `pillar::glimpse()` fails if a data frame has an rvar in it:

```r
> library(posterior)
> data.frame(x = rvar(1:10))
              x
1 5.5 ± 3.02765
> pillar::glimpse(data.frame(x = rvar(1:10)))
Rows: 1
Columns: 1
Error: C stack usage  15922912 is too close to the limit
```

This can be fixed by implementing `pillar::format_glimpse()`, which should be pretty easy. Basically:

- [ ] if vector-like rvar, return character vector of elements converted to a display format. Some variant of `format.rvar()` should work
- [ ] if array-like (2 or more dims), return an abbreviation similar to what matrices / arrays do; e.g. `pillar::format_glimpse(matrix(1:10))` returns `"<matrix[10 x 1]>"`

### PR DESCRIPTION
**Pull request by mjskay**
#### Summary

This PR closes two minor tibble-related issues:

- closes #210 by implementing `pillar::format_glimpse()`. Pillar is already a dependency as it is needed for formating rvar output in tibbles, so this adds no dependencies. Implementing this function allows users of `pillar::glimpse()` to get nice output:

   ```r
   > library(posterior)
   > pillar::glimpse(tibble::tibble(mu = 1:10, x = rvar_rng(rnorm, 10, mu)))
   Rows: 10
   Columns: 2
   $ mu <int> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
   $ x  <rvar> 1 ± 0.97, 2 ± 0.99, 3 ± 1.00, 4 ± 0.99, 5 ± 1.00, 6 ± 1.01, 7 ± 1.00, 8 ± 1.00, 9 ± 1.00~
   ```

- closes #202 by implementing `dplyr::reconstruct()` to remove the `"draws_df"` and `"draws"` classes from a dataframe if {dplyr} verbs drop the metadata columns. For example, the following previously did not work (as reported by @ASKurz [here](https://github.com/stan-dev/posterior/issues/69#issuecomment-914508109)):

   ```r
   > example_draws() %>% as_draws_df() %>% count(.chain)
   # A tibble: 4 x 2
     .chain     n
      <int> <int>
   1      1   100
   2      2   100
   3      3   100
   4      4   100
   ```

   This is slightly trickier as {dplyr} is in Suggests, so to support R < 3.6 we have to register the S3 method in .onLoad rather than `@export`ing it.
   
   **A point of discussion**: unlike with `[.draws_df`, which produces a warning when the `"draws_df"` and `"draws"` classes are dropped, I opted not to do so here as it strikes me that any use of {dplyr} verbs that drop these columns are likely to be operations where the user no longer wants the functionality of the draws class on the result (e.g. summarization). This also makes me wonder if the warning is needed in `[.draws_df`? Happy to discuss alternatives here.

#### Copyright and Licensing

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the following licenses:

- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by mjskay** [comment]
(the CI checks revealed a small problem with casting from rvars to distributional objects in R < 4, so I just fixed that on this PR as well.)

**Review by paul-buerkner — APPROVED** [review]
Thank you! Looks good to me. Waiting for checks to finish before I merge.

**Comment by paul-buerkner** [comment]
It seems the remaining tests don't really want to run at moment. Since checks are passing locally for me too, I am merging this PR now.

**Comment by mjskay** [comment]
Ah yup - that's because Ubuntu 16.04 images are obsolete on github ci now. We'll need to change to 18.04 (I just had to do this on another repo).

**Comment by jgabry** [comment]
Cool, thanks for implementing these!

**Pull request merged**
