### PR TITLE
export helper functions

### PR DESCRIPTION
**Pull request by n-kall**
#### Summary

As discussed in #358, some internal functions could be useful for other packages (including `loo` and `projpred`).

This PR adds documentation to, and exports, the following functions under a new family "helper-functions":

- `ps_khat_threshold`
- `ps_min_ss`
- `ps_tail_length`
- `ps_convergence_rate`
- ~`gpdfit`~ (not exported)

It also updates the PSIS paper reference.

#### Copyright and Licensing

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the following licenses:

- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by mjskay** [comment]
Since these are being exported, would it be good to make the names of functions and arguments follow the same variable naming rules as other public functions? (eg `gpdfit` -> `fit_gp` or `fit_generalized_pareto`; at a first glance parameter names `wip` and `S` also stand out).

**Comment by n-kall** [comment]
`S` has been replaced with `ndraws`, and the `gpdfit` is no longer exported at this time. It is currently exported by `loo`, so we will think further before exporting it too.

**Comment by paul-buerkner** [comment]
Looks good to me. Any changes you want to make before we merge?

**Comment by n-kall** [comment]
I think it should be good now

**Comment by paul-buerkner** [comment]
great! merging now

**Pull request merged**
