### PR TITLE
support tibble::num

### PR DESCRIPTION
**Pull request by paul-buerkner**
This PR implements support for `tibble::num` in `summarise_draws` (issue #257).

@avehtari can you check this out and tell me if that looks reasonable to you?

### CODE REVIEW

**Review by jgabry — APPROVED** [review]
Thanks @paul-buerkner. Code looks good to me!

**Comment by avehtari** [comment]
It's likely that I don't have time to check this until 13th December

**Comment by avehtari** [comment]
Looks good. When testing, I really liked `summary(.num_args=list(sigfig=2,notation="dec"))` (so much faster to read the summary of many rows and columns). Would it be possible to have an option, so that I can set these as my defaults? I couldn't find this in tibble/num documentation

**Comment by paul-buerkner** [comment]
I have now added the global `posterior.num_args` option to control this printing behavior. Once all the checks are completed, I will merge this PR.

**Comment by avehtari** [comment]
Great!

**Pull request merged**
