### PR TITLE
try to fix issue #75

### LINKED ISSUE #75: weight_draws error
```r
x <- example_draws()
weights <- rexp(ndraws(x))
x <- weight_draws(x, weights = weights)

Error in dimnames(out) <- `*vtmp*` : 'dimnames' must be a list
```

### PR DESCRIPTION
**Pull request by paul-buerkner**
This PR should fix #75. @jgabry can you double check?

### CODE REVIEW

**Comment by jgabry** [comment]
yeah will check now

**Comment by jgabry** [comment]
It works, thanks! 

I just pushed a commit to your branch editing the examples a bit to demonstrate more clearly how the original weights can be recovered by using the different arguments to `weights.draws()`. In case you don't like my edits I'll hold off on merging this ;) Feel free to merge if you like my changes or after making more edits

**Comment by jgabry** [comment]
Also, the reason I added those extra examples is because I got confused because the defaults value for the `log` argument of `weights.draws()` is different than `weights.psis()`. That could be an issue going forward...

**Comment by paul-buerkner** [comment]
Thank you! These are really helpful doc edits! Merging this now.

**Comment by paul-buerkner** [comment]
With regard to the `log = FALSE` default, I agree that the different default as compare to .psis is unfortunate but I think that most users expect standard normalized weights from a `weights` method, which should be reflected in the defaults. I am happy to get convinced otherwise of course.

**Pull request merged**
